version: '3.9'

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactions

    ports:
      - "5432:5432"

  redis:
    image: redis:7

    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8000:8000"

    depends_on:
      - postgres
      - redis

  worker:
    build: .

    command: celery -A app.workers.tasks worker --loglevel=info

    depends_on:
      - postgres
      - redis